build:
	protoc -I=$(GOPATH)/src/github.com/yauritux/protobuf/addressbook-svc/proto --go_out=plugins=grpc:$(GOPATH)/src/github.com/yauritux/protobuf/addressbook-svc/messages/addressbook \
		addressbook.proto
