// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

package addressbook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_addressbook_c50dc6e472e039a2, []int{0, 0}
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressbook_c50dc6e472e039a2, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=addressbook.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressbook_c50dc6e472e039a2, []int{0, 0}
}
func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (dst *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(dst, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressbook_c50dc6e472e039a2, []int{1}
}
func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (dst *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(dst, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "addressbook.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "addressbook.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "addressbook.AddressBook")
	proto.RegisterEnum("addressbook.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor_addressbook_c50dc6e472e039a2) }

var fileDescriptor_addressbook_c50dc6e472e039a2 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xcd, 0x36, 0x5d, 0xec, 0x04, 0x4a, 0x1c, 0x45, 0x82, 0x20, 0x86, 0x9c, 0x02, 0x85,
	0x80, 0xf5, 0x20, 0x78, 0xb3, 0x50, 0x50, 0xb4, 0xa6, 0x2c, 0x82, 0x5e, 0x13, 0x32, 0x60, 0x68,
	0x93, 0x59, 0x92, 0x7a, 0xc8, 0xd5, 0x5f, 0x2e, 0xd9, 0x2c, 0x92, 0x83, 0xbd, 0xbd, 0x79, 0x7c,
	0xbc, 0x99, 0x79, 0x70, 0x96, 0x15, 0x45, 0x43, 0x6d, 0x9b, 0x33, 0xef, 0x12, 0xdd, 0xf0, 0x81,
	0xd1, 0x1b, 0x59, 0xd1, 0x8f, 0x00, 0xb9, 0xa5, 0xa6, 0xe5, 0x1a, 0x11, 0xdc, 0x3a, 0xab, 0x28,
	0x70, 0x42, 0x27, 0x9e, 0x29, 0xa3, 0x71, 0x0e, 0xa2, 0x2c, 0x02, 0x11, 0x3a, 0xf1, 0x54, 0x89,
	0xb2, 0xc0, 0x0b, 0x98, 0x52, 0x95, 0x95, 0xfb, 0x60, 0x62, 0xa0, 0x61, 0xc0, 0x7b, 0x90, 0xfa,
	0x8b, 0x6b, 0x6a, 0x03, 0x37, 0x9c, 0xc4, 0xde, 0xf2, 0x26, 0x19, 0x6f, 0x1d, 0xe2, 0x93, 0x6d,
	0x4f, 0xbc, 0x7d, 0x57, 0x39, 0x35, 0xca, 0xe2, 0x57, 0x9f, 0xe0, 0x8d, 0x6c, 0xbc, 0x04, 0x59,
	0x1b, 0x65, 0x6f, 0xb0, 0x13, 0xde, 0x82, 0x7b, 0xe8, 0x34, 0x99, 0x3b, 0xe6, 0xcb, 0xeb, 0xa3,
	0xe9, 0xef, 0x9d, 0x26, 0x65, 0xd0, 0x68, 0x01, 0xb3, 0x3f, 0x0b, 0x01, 0xe4, 0x26, 0x5d, 0x3d,
	0xbf, 0xae, 0xfd, 0x13, 0x3c, 0x05, 0xf7, 0x29, 0xdd, 0xac, 0x7d, 0xa7, 0x57, 0x1f, 0xa9, 0x7a,
	0xf1, 0x45, 0xf4, 0x00, 0xde, 0xe3, 0x10, 0xb9, 0x62, 0xde, 0xe1, 0x02, 0xa4, 0x26, 0xd6, 0xfb,
	0xbe, 0x8a, 0xfe, 0x9d, 0xf3, 0x7f, 0x16, 0x2a, 0x8b, 0xe4, 0xd2, 0x94, 0x7a, 0xf7, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x13, 0x26, 0xc3, 0x8d, 0x69, 0x01, 0x00, 0x00,
}
